### PR TITLE
Update Polish locale.

### PR DESCRIPTION
**Pull request by Sairento-92**

### CODE REVIEW

**Comment by Zetrith** [comment]
New strings have been added for the 1.4 release. Could you update your translation?

**Comment by Sairento-92** [comment]
> 

Done

**Comment by Sairento-92** [comment]
> New strings have been added for the 1.4 release. Could you update your translation?



> New strings have been added for the 1.4 release. Could you update your translation?

Done

**Comment by Sairento-92** [comment]
@Zetrith

**Pull request merged**
